//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR6_Lashkov.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DrinkFactoryEntities : DbContext
    {
        public DrinkFactoryEntities()
            : base("name=DrinkFactoryEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bottles_Operations> Bottles_Operations { get; set; }
        public virtual DbSet<BottleType> BottleType { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Drinks> Drinks { get; set; }
        public virtual DbSet<Drinks_Materials> Drinks_Materials { get; set; }
        public virtual DbSet<Employees> Employees { get; set; }
        public virtual DbSet<Employees_Storage> Employees_Storage { get; set; }
        public virtual DbSet<Employees_Workshop> Employees_Workshop { get; set; }
        public virtual DbSet<Hardware> Hardware { get; set; }
        public virtual DbSet<Hardware_Workshop> Hardware_Workshop { get; set; }
        public virtual DbSet<Materials> Materials { get; set; }
        public virtual DbSet<Materials_Operations> Materials_Operations { get; set; }
        public virtual DbSet<Measures> Measures { get; set; }
        public virtual DbSet<Operation_Type> Operation_Type { get; set; }
        public virtual DbSet<Order_Details> Order_Details { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Plan_Details> Plan_Details { get; set; }
        public virtual DbSet<Plans> Plans { get; set; }
        public virtual DbSet<Positions> Positions { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Shipment_Details> Shipment_Details { get; set; }
        public virtual DbSet<Shipments> Shipments { get; set; }
        public virtual DbSet<Statuses> Statuses { get; set; }
        public virtual DbSet<Storage> Storage { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Workshop> Workshop { get; set; }
    }
}
