//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR6_Lashkov.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Drinks_Materials
    {
        public int drink_id { get; set; }
        public int material_id { get; set; }
        public int measure_id { get; set; }
        public decimal amount { get; set; }
        public int id { get; set; }
    
        public virtual Drinks Drinks { get; set; }
        public virtual Materials Materials { get; set; }
        public virtual Measures Measures { get; set; }
    }
}
