//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR6_Lashkov.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shipment_Details
    {
        public int id { get; set; }
        public int shipment_id { get; set; }
        public int drink_id { get; set; }
        public int bottle_type_id { get; set; }
        public int amount { get; set; }
    
        public virtual BottleType BottleType { get; set; }
        public virtual Drinks Drinks { get; set; }
        public virtual Shipments Shipments { get; set; }
    }
}
